import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "chalachew tsegaye | Software Developer",
  description: "Generated by chalachew tsegaye ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} max-w-screen-xl container mx-auto bg-[#0A192F] text-white`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
